from django.urls import path
from day import views

urlpatterns=[
    path('',views.index),
    path('index',views.index),
    path('login',views.login),
    path('admin',views.admin),
    path('logout',views.logout),
    path('department',views.department),
    path('depupdate',views.depupdate),
    path('depdel',views.depdel),
    path('headdoc',views.headdoc),
    path('headdocupdate',views.headdocupdate),
    path('headdocdel',views.headdocdel),
    path('headnur',views.headnur),
    path('headnurupdate',views.headnurupdate),
    path('headnurdel',views.headnurdel),
    path('rec',views.rec),
    path('recupdate',views.recupdate),
    path('recdel',views.recdel),
    path('doc',views.doc),
    path('docupdate',views.docupdate),
    path('docdel',views.docdel),
    path('docsearch',views.docsearch),
    path('pat',views.pat),
    path('patupdate',views.patupdate),
    path('patdel',views.patdel),
    path('patview',views.patview),
    path('patsearch',views.patsearch),
    path('todaypat',views.todaypat),
    path('recpatsearch',views.recpatsearch),
    path('rectodaypat',views.rectodaypat),
]